### ISSUE TITLE
NuVotifier

### ISSUE THREAD

**Issue by AodX** [Ben12345rocks/VoteForwarder#6]
Hello,
VoteForwarder doesn't work with NuVotifier

on 1.12.1 Votifier stopped working on my server, so i replaced it with NuVotifier 
and now VoteForwarder give me this whenever i get a vote on the main Server
https://hastebin.com/quyebukufu.go

**Comment by Ben12345rocks** [comment]
Votifier works fine. Will look into fixing that though. NuVotifier does have its own voteforwarder built in, could use that if you wanted.

**Comment by AodX** [comment]
can i use it without putting NuVotifier on my bungeecord ?
I want it to be only on 2 servers ( Prison and Factions )

because, last time i had NuVotifier on Bungeecord
it was like, Sending the vote only to the first server you go to 
Then it won't go to the others servers when you go to them

idk :cry:

**Comment by Ben12345rocks** [comment]
No idea, but I think so.

**Comment by AodX** [comment]
and Votifier wasn't working at all, it was giving me Connection Refused on the testing site ( https://minecraftservers.biz/votifier/test/ )
and all the voting sites 
they say, wrong info 

But i just gave the info i had 
weird,

**Comment by Ben12345rocks** [comment]
Just get a new key and port, usually fixes the problem.

**Comment by AodX** [comment]
how ?

**Comment by Ben12345rocks** [comment]
Delete the key folder, change the port...

**Comment by AodX** [comment]
I kept the port, i just Changed the IP to 0.0.0.0
and its working very well :+1:
